- platform: wunderground
  api_key: !secret wu_api_key
  pws_id: !secret wu_pws_id
  monitored_conditions:
    - weather_1d_metric
    - weather_1n_metric
    - weather_2d_metric
    - weather_2n_metric
    - weather_3d_metric
    - weather_3n_metric
    - weather_4d_metric
    - weather_4n_metric
    - temp_high_1d_c
    - temp_c
    - temp_low_1d_c
    - precip_1d
    - precip_1d_mm
    - wind_kph
    - wind_1d_kph
