- platform: spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret
  aliases:
      98120e8ee2621bedd18d954efc6b7de8c3c332a4: 'Amazon Echo Livingroom'
      24b85fae86534f3126e08c4356d112d60063a14f: ' Jørgen's OnePlus 5'
      
